#+TITLE: 空间智能
#+SLUG: spatial-intelligence
#+TYPE: original
#+STATUS: idea
#+PROGRESS: 0
#+TARGET_ALIAS: categories/AI/空间智能
#+TARGET_SUB_ID: auto
#+PIN: false
#+SOURCE_URL:
#+TAGS: [AI, 空间智能, 3D, 世界模型]
#+CREATED_AT: 2026-08-18T10:29:40
#+UPDATED_AT: 2026-08-18T10:29:40
#+PUBLISHED_AT:
#+PUBLISHED_FILE:

* 空间智能

空间智能是什么呢？

1983年，教育心理学家霍华德·加德纳在著作中提出了多元智能理论。在这个理论框架中，总共有 7 个人类的核心智能，其中就有空间智能、逻辑数学智能、音乐智能、语言智能、身体动觉智能、人际智能以及自省智能。空间智能正属于人类的 7 种智能之一。

最早是以 ImageNet 为代表的一些数据集，将机器在视觉上理解世界的能力提升到了一个新高度。AlexNet 引入的以及 CNN 这些技术，让模型能够拥有更强的视觉能力。

从二维到三维：SLAM。以 SLAM 为代表的一系列技术，让 AI 能够从二维理解世界，进步到从三维的角度去建模、理解世界。

理解和生成世界：NeRF、生成式模型、世界模型。由于生成式模型的发展，我们的模型可以在三维条件下理解并生成世界，从而自主规划路径、重建空间结构、预测未来的行动方向。

空间智能：计算机视觉、机器人、生成模型。空间智能就是把计算机视觉、机器人以及生成模型这多条技术路径的技术汇合产生的一种技术方向吧，或者技术领域。

空间智能主要包括在潜空间对空间进行预测，以及对空间去进行生成2条路线。

对空间生成这一条路线，需要对生成显示的 3D 资产这一条路线。比较有代表性的就是李飞飞的 World Labs。而另一条路线在浅空间进行规划，主要一个代表就是杨立昆的 JEPA 模型。
其中空间生产包括重建、推断及生存，不过现在一般来说这些路线可能会有交叉或者说是被合并.

传统的 3D 建模方法一般包括点云以及 mesh，点云就是点，mesh 就是面片。近年来因为 NeRF 的发展，就有了神经渲染的一个路线；之后现在又有了 3DGS 这一些空间表示方法，最近被越来越大范围地应用。

3D高斯的优点在于能够近乎完美地表示物理世界的视觉效果，但缺点在于交互方面表现不佳，未来或许能通过技术探索解决这一问题。
